-- Restores the "starter vocabulary" pack that V9 originally seeded, this time scoped per user
-- instead of global. V11 (multi-tenancy retrofit) truncated all vocabulary including V9's seed,
-- since it had no owner — every account, including brand-new ones, was left with an empty
-- vocabulary list, which defeats the point of a "starter pack" (see decision D18 follow-up).
--
-- Design: a reserved system account ('seed@learnflow.system', never logged into — no UI path
-- creates or authenticates it, and its bcrypt hash is of a random string nobody knows) owns the
-- canonical 300-word template (EN CEFR A1/A2, ZH HSK1/HSK2, JA N5/N4 — same content V9 seeded,
-- copied verbatim). Both this migration's one-time backfill (for every account that existed
-- before this fix) and every future registration (VocabularyService.seedStarterVocabularyFor,
-- called from AuthService.register) clone FROM this template's rows, instead of duplicating the
-- 300-word list a second time in application code.

INSERT INTO app_user (email, password_hash, display_name, created_at)
VALUES (
    'seed@learnflow.system',
    -- bcrypt hash of a random 32-byte string generated at authoring time; nobody has the
    -- plaintext, and there is no registration/login path that would ever target this email.
    '$2a$10$M5mRfnP8Ix4wQFhrAAax7OJMXkgSbpw0/Coe9XYaJgD9VgppTIqJ.',
    'LearnFlow Starter Pack',
    now()
);

INSERT INTO vocabulary_tag (user_id, name)
SELECT (SELECT id FROM app_user WHERE email = 'seed@learnflow.system'), t.name
FROM (VALUES ('A1'), ('A2'), ('HSK1'), ('HSK2'), ('N5'), ('N4')) AS t (name);

-- Same 300-word list V9 originally seeded, now owned by the template account above.
INSERT INTO vocabulary (user_id, language_id, word, meaning, example, attributes, created_at, updated_at)
SELECT
    (SELECT id FROM app_user WHERE email = 'seed@learnflow.system'),
    seed.language_id, seed.word, seed.meaning, seed.example, seed.attributes, now(), now()
FROM (VALUES
  ((SELECT id FROM language WHERE code = 'en'), 'action', 'hành động', 'The movie has a lot of action.', '{"ipa": "/ˈækʃn/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'activity', 'hoạt động', 'Swimming is my favorite activity.', '{"ipa": "/ækˈtɪvəti/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'actor', 'diễn viên (nam)', 'He wants to be an actor.', '{"ipa": "/ˈæktər/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'address', 'địa chỉ', 'What is your home address?', '{"ipa": "/ˈædres/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'adult', 'người lớn', 'This movie is only for adults.', '{"ipa": "/ˈædʌlt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'advice', 'lời khuyên', 'Can you give me some advice?', '{"ipa": "/ədˈvaɪs/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'afraid', 'sợ hãi', 'I am afraid of dogs.', '{"ipa": "/əˈfreɪd/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'afternoon', 'buổi chiều', 'See you this afternoon.', '{"ipa": "/ˌæftərˈnuːn/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'age', 'tuổi', 'What is your age?', '{"ipa": "/eɪdʒ/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'agree', 'đồng ý', 'I agree with you.', '{"ipa": "/əˈɡriː/", "partOfSpeech": "verb", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'air', 'không khí', 'The air here is very clean.', '{"ipa": "/er/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'airport', 'sân bay', 'We arrived at the airport early.', '{"ipa": "/ˈerpɔːrt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'angry', 'tức giận', 'She was angry with me.', '{"ipa": "/ˈæŋɡri/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'animal', 'động vật', 'A dog is an animal.', '{"ipa": "/ˈænɪml/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'apartment', 'căn hộ', 'They live in a small apartment.', '{"ipa": "/əˈpɑːrtmənt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'apple', 'quả táo', 'I eat an apple every morning.', '{"ipa": "/ˈæpl/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'area', 'khu vực', 'This is a quiet area.', '{"ipa": "/ˈeriə/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'arm', 'cánh tay', 'He broke his arm.', '{"ipa": "/ɑːrm/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'arrive', 'đến nơi', 'The train will arrive at six.', '{"ipa": "/əˈraɪv/", "partOfSpeech": "verb", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'art', 'nghệ thuật', 'She studies art at school.', '{"ipa": "/ɑːrt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'artist', 'nghệ sĩ', 'He is a famous artist.', '{"ipa": "/ˈɑːrtɪst/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'ask', 'hỏi', 'Can I ask you a question?', '{"ipa": "/æsk/", "partOfSpeech": "verb", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'aunt', 'cô/dì', 'My aunt lives in Hanoi.', '{"ipa": "/ænt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'baby', 'em bé', 'The baby is sleeping.', '{"ipa": "/ˈbeɪbi/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bad', 'tệ, xấu', 'The weather is bad today.', '{"ipa": "/bæd/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bag', 'cái túi', 'I put my books in my bag.', '{"ipa": "/bæɡ/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'ball', 'quả bóng', 'The children are playing with a ball.', '{"ipa": "/bɔːl/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'banana', 'quả chuối', 'She is eating a banana.', '{"ipa": "/bəˈnænə/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bank', 'ngân hàng', 'I need to go to the bank.', '{"ipa": "/bæŋk/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'baseball', 'bóng chày', 'They play baseball on Sundays.', '{"ipa": "/ˈbeɪsbɔːl/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'basketball', 'bóng rổ', 'He is good at basketball.', '{"ipa": "/ˈbæskɪtbɔːl/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bath', 'bồn tắm', 'I take a bath every night.', '{"ipa": "/bæθ/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bathroom', 'phòng tắm', 'The bathroom is upstairs.', '{"ipa": "/ˈbæθruːm/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'beach', 'bãi biển', 'We spent the day at the beach.', '{"ipa": "/biːtʃ/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'beautiful', 'đẹp', 'This garden is beautiful.', '{"ipa": "/ˈbjuːtɪfl/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bed', 'giường', 'I go to bed at ten.', '{"ipa": "/bed/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bedroom', 'phòng ngủ', 'My bedroom is very small.', '{"ipa": "/ˈbedruːm/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'begin', 'bắt đầu', 'The class will begin soon.', '{"ipa": "/bɪˈɡɪn/", "partOfSpeech": "verb", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'believe', 'tin tưởng', 'I believe you.', '{"ipa": "/bɪˈliːv/", "partOfSpeech": "verb", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'best', 'tốt nhất', 'She is my best friend.', '{"ipa": "/best/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bicycle', 'xe đạp', 'He rides his bicycle to school.', '{"ipa": "/ˈbaɪsɪkl/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'big', 'to lớn', 'They live in a big house.', '{"ipa": "/bɪɡ/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bird', 'con chim', 'A bird is singing outside.', '{"ipa": "/bɜːrd/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'birthday', 'sinh nhật', 'Today is my birthday.', '{"ipa": "/ˈbɜːrθdeɪ/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'black', 'màu đen', 'She has a black cat.', '{"ipa": "/blæk/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'blue', 'màu xanh dương', 'The sky is blue.', '{"ipa": "/bluː/", "partOfSpeech": "adjective", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'boat', 'thuyền', 'We took a boat across the lake.', '{"ipa": "/boʊt/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'body', 'cơ thể', 'Exercise is good for your body.', '{"ipa": "/ˈbɑːdi/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'book', 'quyển sách', 'I am reading a good book.', '{"ipa": "/bʊk/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bread', 'bánh mì', 'We buy fresh bread every day.', '{"ipa": "/bred/", "partOfSpeech": "noun", "cefrLevel": "A1"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'ability', 'khả năng', 'She has the ability to solve hard problems.', '{"ipa": "/əˈbɪləti/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'able', 'có thể', 'He is able to swim very fast.', '{"ipa": "/ˈeɪbl/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'accept', 'chấp nhận', 'I accept your offer.', '{"ipa": "/əkˈsept/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'accident', 'tai nạn', 'There was a car accident this morning.', '{"ipa": "/ˈæksɪdənt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'achieve', 'đạt được', 'She worked hard to achieve her goal.', '{"ipa": "/əˈtʃiːv/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'active', 'năng động', 'My grandfather is still very active.', '{"ipa": "/ˈæktɪv/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'adventure', 'cuộc phiêu lưu', 'The trip was a great adventure.', '{"ipa": "/ədˈventʃər/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'advertisement', 'quảng cáo', 'I saw an advertisement for a new phone.', '{"ipa": "/ˌædvərˈtaɪzmənt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'alive', 'còn sống', 'Her grandmother is still alive.', '{"ipa": "/əˈlaɪv/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'allow', 'cho phép', 'My parents allow me to stay out late.', '{"ipa": "/əˈlaʊ/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'alone', 'một mình', 'He lives alone in the city.', '{"ipa": "/əˈloʊn/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'already', 'đã rồi', 'I have already finished my homework.', '{"ipa": "/ɔːlˈredi/", "partOfSpeech": "adverb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'amount', 'số lượng', 'We need a large amount of money.', '{"ipa": "/əˈmaʊnt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'ancient', 'cổ xưa', 'They visited an ancient temple.', '{"ipa": "/ˈeɪnʃənt/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'ankle', 'mắt cá chân', 'He hurt his ankle playing football.', '{"ipa": "/ˈæŋkl/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'appear', 'xuất hiện', 'The sun began to appear behind the clouds.', '{"ipa": "/əˈpɪr/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'appearance', 'vẻ ngoài', 'Her appearance surprised everyone.', '{"ipa": "/əˈpɪrəns/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'apply', 'nộp đơn', 'I want to apply for this job.', '{"ipa": "/əˈplaɪ/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'architect', 'kiến trúc sư', 'My sister is an architect.', '{"ipa": "/ˈɑːrkɪtekt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'architecture', 'kiến trúc', 'The city is famous for its architecture.', '{"ipa": "/ˈɑːrkɪtektʃər/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'argue', 'tranh cãi', 'They often argue about small things.', '{"ipa": "/ˈɑːrɡjuː/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'argument', 'cuộc tranh cãi', 'We had an argument yesterday.', '{"ipa": "/ˈɑːrɡjumənt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'army', 'quân đội', 'His father served in the army.', '{"ipa": "/ˈɑːrmi/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'assistant', 'trợ lý', 'She works as a shop assistant.', '{"ipa": "/əˈsɪstənt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'athlete', 'vận động viên', 'He trains like a professional athlete.', '{"ipa": "/ˈæθliːt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'attack', 'cuộc tấn công', 'The city suffered a sudden attack.', '{"ipa": "/əˈtæk/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'attend', 'tham dự', 'I will attend the meeting tomorrow.', '{"ipa": "/əˈtend/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'attention', 'sự chú ý', 'Please pay attention to the teacher.', '{"ipa": "/əˈtenʃn/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'attractive', 'hấp dẫn', 'The offer looks very attractive.', '{"ipa": "/əˈtræktɪv/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'audience', 'khán giả', 'The audience clapped loudly.', '{"ipa": "/ˈɔːdiəns/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'author', 'tác giả', 'Who is the author of this book?', '{"ipa": "/ˈɔːθər/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'available', 'có sẵn', 'The tickets are still available.', '{"ipa": "/əˈveɪləbl/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'avoid', 'tránh', 'You should avoid eating too much sugar.', '{"ipa": "/əˈvɔɪd/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'award', 'giải thưởng', 'She won an award for her painting.', '{"ipa": "/əˈwɔːrd/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'awful', 'kinh khủng', 'The weather was awful yesterday.', '{"ipa": "/ˈɔːfl/", "partOfSpeech": "adjective", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'background', 'bối cảnh', 'Tell me about your family background.', '{"ipa": "/ˈbækɡraʊnd/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bean', 'hạt đậu', 'We grow beans in our garden.', '{"ipa": "/biːn/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bear', 'con gấu', 'We saw a bear in the forest.', '{"ipa": "/ber/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'beef', 'thịt bò', 'She cooked beef for dinner.', '{"ipa": "/biːf/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'behavior', 'hành vi', 'His behavior surprised his teacher.', '{"ipa": "/bɪˈheɪvjər/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'belong', 'thuộc về', 'This book belongs to me.', '{"ipa": "/bɪˈlɔːŋ/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'belt', 'thắt lưng', 'He is wearing a brown belt.', '{"ipa": "/belt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'benefit', 'lợi ích', 'Exercise has many health benefits.', '{"ipa": "/ˈbenɪfɪt/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'biology', 'sinh học', 'She studies biology at university.', '{"ipa": "/baɪˈɑːlədʒi/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'birth', 'sự sinh ra', 'What is your date of birth?', '{"ipa": "/bɜːrθ/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'blood', 'máu', 'The doctor took a blood sample.', '{"ipa": "/blʌd/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'boil', 'đun sôi', 'Please boil some water for tea.', '{"ipa": "/bɔɪl/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'bone', 'xương', 'The dog is chewing on a bone.', '{"ipa": "/boʊn/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'borrow', 'mượn', 'Can I borrow your pen?', '{"ipa": "/ˈbɑːroʊ/", "partOfSpeech": "verb", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'en'), 'boss', 'sếp', 'My boss is very kind.', '{"ipa": "/bɔːs/", "partOfSpeech": "noun", "cefrLevel": "A2"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '爸爸', 'bố', '我爸爸是老师。', '{"pinyin": "bàba", "hskLevel": "HSK1", "examplePinyin": "Wǒ bàba shì lǎoshī."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '妈妈', 'mẹ', '我妈妈很漂亮。', '{"pinyin": "māma", "hskLevel": "HSK1", "examplePinyin": "Wǒ māma hěn piàoliang."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '儿子', 'con trai', '他有一个儿子。', '{"pinyin": "érzi", "hskLevel": "HSK1", "examplePinyin": "Tā yǒu yí ge érzi."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '女儿', 'con gái', '她的女儿在学校。', '{"pinyin": "nǚ''ér", "hskLevel": "HSK1", "examplePinyin": "Tā de nǚ''ér zài xuéxiào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '老师', 'giáo viên', '我的老师很好。', '{"pinyin": "lǎoshī", "hskLevel": "HSK1", "examplePinyin": "Wǒ de lǎoshī hěn hǎo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '学生', 'học sinh', '他是一个学生。', '{"pinyin": "xuéshēng", "hskLevel": "HSK1", "examplePinyin": "Tā shì yí ge xuéshēng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '同学', 'bạn học', '他是我的同学。', '{"pinyin": "tóngxué", "hskLevel": "HSK1", "examplePinyin": "Tā shì wǒ de tóngxué."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '朋友', 'bạn bè', '她是我的朋友。', '{"pinyin": "péngyǒu", "hskLevel": "HSK1", "examplePinyin": "Tā shì wǒ de péngyǒu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '医生', 'bác sĩ', '他是一名医生。', '{"pinyin": "yīshēng", "hskLevel": "HSK1", "examplePinyin": "Tā shì yì míng yīshēng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '衣服', 'quần áo', '这件衣服很漂亮。', '{"pinyin": "yīfu", "hskLevel": "HSK1", "examplePinyin": "Zhè jiàn yīfu hěn piàoliang."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '水', 'nước', '我想喝水。', '{"pinyin": "shuǐ", "hskLevel": "HSK1", "examplePinyin": "Wǒ xiǎng hē shuǐ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '菜', 'món ăn', '这个菜很好吃。', '{"pinyin": "cài", "hskLevel": "HSK1", "examplePinyin": "Zhège cài hěn hǎochī."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '米饭', 'cơm', '我喜欢吃米饭。', '{"pinyin": "mǐfàn", "hskLevel": "HSK1", "examplePinyin": "Wǒ xǐhuān chī mǐfàn."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '水果', 'trái cây', '我每天吃水果。', '{"pinyin": "shuǐguǒ", "hskLevel": "HSK1", "examplePinyin": "Wǒ měitiān chī shuǐguǒ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '苹果', 'quả táo', '我买了两个苹果。', '{"pinyin": "píngguǒ", "hskLevel": "HSK1", "examplePinyin": "Wǒ mǎile liǎng ge píngguǒ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '茶', 'trà', '他喜欢喝茶。', '{"pinyin": "chá", "hskLevel": "HSK1", "examplePinyin": "Tā xǐhuān hē chá."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '杯子', 'cái cốc', '这个杯子是我的。', '{"pinyin": "bēizi", "hskLevel": "HSK1", "examplePinyin": "Zhège bēizi shì wǒ de."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '钱', 'tiền', '我没有钱。', '{"pinyin": "qián", "hskLevel": "HSK1", "examplePinyin": "Wǒ méiyǒu qián."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '飞机', 'máy bay', '我们坐飞机去北京。', '{"pinyin": "fēijī", "hskLevel": "HSK1", "examplePinyin": "Wǒmen zuò fēijī qù Běijīng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '出租车', 'taxi', '我们坐出租车回家。', '{"pinyin": "chūzūchē", "hskLevel": "HSK1", "examplePinyin": "Wǒmen zuò chūzūchē huí jiā."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '电视', 'ti vi', '他在看电视。', '{"pinyin": "diànshì", "hskLevel": "HSK1", "examplePinyin": "Tā zài kàn diànshì."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '电脑', 'máy tính', '我的电脑坏了。', '{"pinyin": "diànnǎo", "hskLevel": "HSK1", "examplePinyin": "Wǒ de diànnǎo huài le."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '电影', 'phim', '我们去看电影吧。', '{"pinyin": "diànyǐng", "hskLevel": "HSK1", "examplePinyin": "Wǒmen qù kàn diànyǐng ba."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '天气', 'thời tiết', '今天天气很好。', '{"pinyin": "tiānqì", "hskLevel": "HSK1", "examplePinyin": "Jīntiān tiānqì hěn hǎo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '猫', 'con mèo', '我家有一只猫。', '{"pinyin": "māo", "hskLevel": "HSK1", "examplePinyin": "Wǒ jiā yǒu yì zhī māo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '狗', 'con chó', '他有一只狗。', '{"pinyin": "gǒu", "hskLevel": "HSK1", "examplePinyin": "Tā yǒu yì zhī gǒu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '东西', 'đồ vật', '这是什么东西？', '{"pinyin": "dōngxi", "hskLevel": "HSK1", "examplePinyin": "Zhè shì shénme dōngxi?"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '人', 'người', '这里有很多人。', '{"pinyin": "rén", "hskLevel": "HSK1", "examplePinyin": "Zhèlǐ yǒu hěn duō rén."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '名字', 'tên', '你叫什么名字？', '{"pinyin": "míngzi", "hskLevel": "HSK1", "examplePinyin": "Nǐ jiào shénme míngzi?"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '书', 'sách', '我在看一本书。', '{"pinyin": "shū", "hskLevel": "HSK1", "examplePinyin": "Wǒ zài kàn yì běn shū."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '桌子', 'cái bàn', '书在桌子上。', '{"pinyin": "zhuōzi", "hskLevel": "HSK1", "examplePinyin": "Shū zài zhuōzi shàng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '椅子', 'cái ghế', '请坐在椅子上。', '{"pinyin": "yǐzi", "hskLevel": "HSK1", "examplePinyin": "Qǐng zuò zài yǐzi shàng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '是', 'là', '他是我的朋友。', '{"pinyin": "shì", "hskLevel": "HSK1", "examplePinyin": "Tā shì wǒ de péngyǒu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '有', 'có', '我有一本书。', '{"pinyin": "yǒu", "hskLevel": "HSK1", "examplePinyin": "Wǒ yǒu yì běn shū."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '看', 'xem, nhìn', '我喜欢看书。', '{"pinyin": "kàn", "hskLevel": "HSK1", "examplePinyin": "Wǒ xǐhuān kàn shū."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '听', 'nghe', '他在听音乐。', '{"pinyin": "tīng", "hskLevel": "HSK1", "examplePinyin": "Tā zài tīng yīnyuè."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '说', 'nói', '请说中文。', '{"pinyin": "shuō", "hskLevel": "HSK1", "examplePinyin": "Qǐng shuō Zhōngwén."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '读', 'đọc', '他每天读书。', '{"pinyin": "dú", "hskLevel": "HSK1", "examplePinyin": "Tā měitiān dú shū."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '写', 'viết', '我在写字。', '{"pinyin": "xiě", "hskLevel": "HSK1", "examplePinyin": "Wǒ zài xiě zì."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '来', 'đến', '他明天来我家。', '{"pinyin": "lái", "hskLevel": "HSK1", "examplePinyin": "Tā míngtiān lái wǒ jiā."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '去', 'đi', '我们去学校。', '{"pinyin": "qù", "hskLevel": "HSK1", "examplePinyin": "Wǒmen qù xuéxiào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '吃', 'ăn', '我们一起吃饭吧。', '{"pinyin": "chī", "hskLevel": "HSK1", "examplePinyin": "Wǒmen yìqǐ chīfàn ba."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '喝', 'uống', '我想喝茶。', '{"pinyin": "hē", "hskLevel": "HSK1", "examplePinyin": "Wǒ xiǎng hē chá."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '睡觉', 'ngủ', '我十点睡觉。', '{"pinyin": "shuìjiào", "hskLevel": "HSK1", "examplePinyin": "Wǒ shí diǎn shuìjiào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '买', 'mua', '我要买水果。', '{"pinyin": "mǎi", "hskLevel": "HSK1", "examplePinyin": "Wǒ yào mǎi shuǐguǒ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '学习', 'học tập', '我在学习中文。', '{"pinyin": "xuéxí", "hskLevel": "HSK1", "examplePinyin": "Wǒ zài xuéxí Zhōngwén."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '工作', 'làm việc', '他在银行工作。', '{"pinyin": "gōngzuò", "hskLevel": "HSK1", "examplePinyin": "Tā zài yínháng gōngzuò."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '好', 'tốt', '这个主意很好。', '{"pinyin": "hǎo", "hskLevel": "HSK1", "examplePinyin": "Zhège zhǔyi hěn hǎo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '大', 'to, lớn', '这个房子很大。', '{"pinyin": "dà", "hskLevel": "HSK1", "examplePinyin": "Zhège fángzi hěn dà."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '小', 'nhỏ', '这只猫很小。', '{"pinyin": "xiǎo", "hskLevel": "HSK1", "examplePinyin": "Zhè zhī māo hěn xiǎo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '哥哥', 'anh trai', '我哥哥在北京工作。', '{"pinyin": "gēge", "hskLevel": "HSK2", "examplePinyin": "Wǒ gēge zài Běijīng gōngzuò."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '姐姐', 'chị gái', '我姐姐是医生。', '{"pinyin": "jiějie", "hskLevel": "HSK2", "examplePinyin": "Wǒ jiějie shì yīshēng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '弟弟', 'em trai', '我弟弟在学校。', '{"pinyin": "dìdi", "hskLevel": "HSK2", "examplePinyin": "Wǒ dìdi zài xuéxiào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '妹妹', 'em gái', '我妹妹很可爱。', '{"pinyin": "mèimei", "hskLevel": "HSK2", "examplePinyin": "Wǒ mèimei hěn kě''ài."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '丈夫', 'chồng', '她的丈夫是老师。', '{"pinyin": "zhàngfu", "hskLevel": "HSK2", "examplePinyin": "Tā de zhàngfu shì lǎoshī."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '妻子', 'vợ', '他的妻子很漂亮。', '{"pinyin": "qīzi", "hskLevel": "HSK2", "examplePinyin": "Tā de qīzi hěn piàoliang."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '孩子', 'con cái, trẻ em', '他们有两个孩子。', '{"pinyin": "háizi", "hskLevel": "HSK2", "examplePinyin": "Tāmen yǒu liǎng ge háizi."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '男人', 'đàn ông', '那个男人是我爸爸。', '{"pinyin": "nánrén", "hskLevel": "HSK2", "examplePinyin": "Nàge nánrén shì wǒ bàba."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '女人', 'phụ nữ', '那个女人是我妈妈。', '{"pinyin": "nǚrén", "hskLevel": "HSK2", "examplePinyin": "Nàge nǚrén shì wǒ māma."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '服务员', 'nhân viên phục vụ', '服务员，请给我菜单。', '{"pinyin": "fúwùyuán", "hskLevel": "HSK2", "examplePinyin": "Fúwùyuán, qǐng gěi wǒ càidān."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '鱼', 'cá', '我们晚上吃鱼。', '{"pinyin": "yú", "hskLevel": "HSK2", "examplePinyin": "Wǒmen wǎnshàng chī yú."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '牛奶', 'sữa bò', '我每天喝牛奶。', '{"pinyin": "niúnǎi", "hskLevel": "HSK2", "examplePinyin": "Wǒ měitiān hē niúnǎi."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '鸡蛋', 'trứng gà', '早上我吃鸡蛋。', '{"pinyin": "jīdàn", "hskLevel": "HSK2", "examplePinyin": "Zǎoshàng wǒ chī jīdàn."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '西瓜', 'dưa hấu', '夏天我喜欢吃西瓜。', '{"pinyin": "xīguā", "hskLevel": "HSK2", "examplePinyin": "Xiàtiān wǒ xǐhuān chī xīguā."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '咖啡', 'cà phê', '他每天喝咖啡。', '{"pinyin": "kāfēi", "hskLevel": "HSK2", "examplePinyin": "Tā měitiān hē kāfēi."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '雪', 'tuyết', '外面下雪了。', '{"pinyin": "xuě", "hskLevel": "HSK2", "examplePinyin": "Wàimiàn xiàxuě le."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '药', 'thuốc', '你要吃药了。', '{"pinyin": "yào", "hskLevel": "HSK2", "examplePinyin": "Nǐ yào chī yào le."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '手机', 'điện thoại di động', '我的手机不见了。', '{"pinyin": "shǒujī", "hskLevel": "HSK2", "examplePinyin": "Wǒ de shǒujī bú jiàn le."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '手表', 'đồng hồ đeo tay', '这块手表很贵。', '{"pinyin": "shǒubiǎo", "hskLevel": "HSK2", "examplePinyin": "Zhè kuài shǒubiǎo hěn guì."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '眼睛', 'đôi mắt', '她的眼睛很大。', '{"pinyin": "yǎnjīng", "hskLevel": "HSK2", "examplePinyin": "Tā de yǎnjīng hěn dà."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '身体', 'cơ thể, sức khỏe', '多运动对身体好。', '{"pinyin": "shēntǐ", "hskLevel": "HSK2", "examplePinyin": "Duō yùndòng duì shēntǐ hǎo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '公共汽车', 'xe buýt', '我坐公共汽车上班。', '{"pinyin": "gōnggòngqìchē", "hskLevel": "HSK2", "examplePinyin": "Wǒ zuò gōnggòngqìchē shàngbān."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '报纸', 'báo giấy', '爸爸在看报纸。', '{"pinyin": "bàozhǐ", "hskLevel": "HSK2", "examplePinyin": "Bàba zài kàn bàozhǐ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '门', 'cửa', '请把门关上。', '{"pinyin": "mén", "hskLevel": "HSK2", "examplePinyin": "Qǐng bǎ mén guānshàng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '课', 'bài học, tiết học', '我们今天有中文课。', '{"pinyin": "kè", "hskLevel": "HSK2", "examplePinyin": "Wǒmen jīntiān yǒu Zhōngwén kè."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '问题', 'câu hỏi, vấn đề', '我有一个问题。', '{"pinyin": "wèntí", "hskLevel": "HSK2", "examplePinyin": "Wǒ yǒu yí ge wèntí."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '考试', 'kỳ thi', '明天我们有考试。', '{"pinyin": "kǎoshì", "hskLevel": "HSK2", "examplePinyin": "Míngtiān wǒmen yǒu kǎoshì."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '票', 'vé', '我买了两张票。', '{"pinyin": "piào", "hskLevel": "HSK2", "examplePinyin": "Wǒ mǎile liǎng zhāng piào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '颜色', 'màu sắc', '你喜欢什么颜色？', '{"pinyin": "yánsè", "hskLevel": "HSK2", "examplePinyin": "Nǐ xǐhuān shénme yánsè?"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '铅笔', 'bút chì', '这支铅笔是我的。', '{"pinyin": "qiānbǐ", "hskLevel": "HSK2", "examplePinyin": "Zhè zhī qiānbǐ shì wǒ de."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '面条', 'mì sợi', '我中午吃面条。', '{"pinyin": "miàntiáo", "hskLevel": "HSK2", "examplePinyin": "Wǒ zhōngwǔ chī miàntiáo."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '火车站', 'ga tàu hỏa', '火车站离这儿很近。', '{"pinyin": "huǒchēzhàn", "hskLevel": "HSK2", "examplePinyin": "Huǒchēzhàn lí zhèr hěn jìn."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '公司', 'công ty', '他在一家大公司工作。', '{"pinyin": "gōngsī", "hskLevel": "HSK2", "examplePinyin": "Tā zài yì jiā dà gōngsī gōngzuò."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '宾馆', 'khách sạn', '我们住在这家宾馆。', '{"pinyin": "bīnguǎn", "hskLevel": "HSK2", "examplePinyin": "Wǒmen zhù zài zhè jiā bīnguǎn."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '说话', 'nói chuyện', '请不要说话。', '{"pinyin": "shuōhuà", "hskLevel": "HSK2", "examplePinyin": "Qǐng bú yào shuōhuà."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '走', 'đi bộ', '我们走路去公园。', '{"pinyin": "zǒu", "hskLevel": "HSK2", "examplePinyin": "Wǒmen zǒulù qù gōngyuán."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '跑步', 'chạy bộ', '他每天早上跑步。', '{"pinyin": "pǎobù", "hskLevel": "HSK2", "examplePinyin": "Tā měitiān zǎoshàng pǎobù."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '穿', 'mặc (quần áo)', '她穿着一件红色的衣服。', '{"pinyin": "chuān", "hskLevel": "HSK2", "examplePinyin": "Tā chuānzhe yí jiàn hóngsè de yīfu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '洗', 'rửa, giặt', '我每天洗衣服。', '{"pinyin": "xǐ", "hskLevel": "HSK2", "examplePinyin": "Wǒ měitiān xǐ yīfu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '找', 'tìm', '你在找什么？', '{"pinyin": "zhǎo", "hskLevel": "HSK2", "examplePinyin": "Nǐ zài zhǎo shénme?"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '笑', 'cười', '孩子们在笑。', '{"pinyin": "xiào", "hskLevel": "HSK2", "examplePinyin": "Háizimen zài xiào."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '开始', 'bắt đầu', '电影开始了。', '{"pinyin": "kāishǐ", "hskLevel": "HSK2", "examplePinyin": "Diànyǐng kāishǐ le."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '帮助', 'giúp đỡ', '谢谢你帮助我。', '{"pinyin": "bāngzhù", "hskLevel": "HSK2", "examplePinyin": "Xièxie nǐ bāngzhù wǒ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '起床', 'thức dậy', '我每天七点起床。', '{"pinyin": "qǐchuáng", "hskLevel": "HSK2", "examplePinyin": "Wǒ měitiān qī diǎn qǐchuáng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '唱歌', 'hát', '她很会唱歌。', '{"pinyin": "chànggē", "hskLevel": "HSK2", "examplePinyin": "Tā hěn huì chànggē."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '跳舞', 'nhảy múa', '他们喜欢跳舞。', '{"pinyin": "tiàowǔ", "hskLevel": "HSK2", "examplePinyin": "Tāmen xǐhuān tiàowǔ."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '旅游', 'du lịch', '我们暑假去旅游。', '{"pinyin": "lǚyóu", "hskLevel": "HSK2", "examplePinyin": "Wǒmen shǔjià qù lǚyóu."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '游泳', 'bơi lội', '夏天我常常游泳。', '{"pinyin": "yóuyǒng", "hskLevel": "HSK2", "examplePinyin": "Xiàtiān wǒ chángcháng yóuyǒng."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '红', 'màu đỏ', '她喜欢红色的花。', '{"pinyin": "hóng", "hskLevel": "HSK2", "examplePinyin": "Tā xǐhuān hóngsè de huā."}'::jsonb),
  ((SELECT id FROM language WHERE code = 'zh'), '快乐', 'vui vẻ, hạnh phúc', '祝你生日快乐！', '{"pinyin": "kuàilè", "hskLevel": "HSK2", "examplePinyin": "Zhù nǐ shēngrì kuàilè!"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '青い', 'màu xanh (da trời)', '空は青いです。', '{"reading": "あおい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "そらはあおいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '赤い', 'màu đỏ', 'リンゴは赤いです。', '{"reading": "あかい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "りんごはあかいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '秋', 'mùa thu', '秋は涼しいです。', '{"reading": "あき", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あきはすずしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '朝', 'buổi sáng', '朝ご飯を食べます。', '{"reading": "あさ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あさごはんをたべます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '朝御飯', 'bữa sáng', '朝御飯はパンです。', '{"reading": "あさごはん", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あさごはんはパンです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '明日', 'ngày mai', '明日学校に行きます。', '{"reading": "あした", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あしたがっこうにいきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '足', 'chân', '足が痛いです。', '{"reading": "あし", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あしがいたいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '遊ぶ', 'chơi', '公園で遊びます。', '{"reading": "あそぶ", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "こうえんであそびます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '暖かい', 'ấm áp', '今日は暖かいです。', '{"reading": "あたたかい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "きょうはあたたかいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '頭', 'đầu (cơ thể)', '頭が痛いです。', '{"reading": "あたま", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あたまがいたいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '新しい', 'mới', '新しい本を買いました。', '{"reading": "あたらしい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "あたらしいほんをかいました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '暑い', 'nóng (thời tiết)', '夏は暑いです。', '{"reading": "あつい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "なつはあついです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '雨', 'mưa', '今日は雨です。', '{"reading": "あめ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "きょうはあめです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '洗う', 'rửa, giặt', '手を洗います。', '{"reading": "あらう", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "てをあらいます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '歩く', 'đi bộ', '毎日歩きます。', '{"reading": "あるく", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "まいにちあるきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '家', 'nhà', '家に帰ります。', '{"reading": "いえ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いえにかえります。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '行く', 'đi', '学校に行きます。', '{"reading": "いく", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "がっこうにいきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '医者', 'bác sĩ', '父は医者です。', '{"reading": "いしゃ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "ちちはいしゃです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '椅子', 'cái ghế', '椅子に座ります。', '{"reading": "いす", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いすにすわります。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '忙しい', 'bận rộn', '今日は忙しいです。', '{"reading": "いそがしい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "きょうはいそがしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '一日', 'một ngày', '一日中働きます。', '{"reading": "いちにち", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いちにちじゅうはたらきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '犬', 'con chó', '犬が好きです。', '{"reading": "いぬ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いぬがすきです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '今', 'bây giờ', '今何時ですか。', '{"reading": "いま", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いまなんじですか。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '意味', 'ý nghĩa', 'この言葉の意味は何ですか。', '{"reading": "いみ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "このことばのいみはなんですか。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '妹', 'em gái', '妹は学生です。', '{"reading": "いもうと", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "いもうとはがくせいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '色', 'màu sắc', '好きな色は何ですか。', '{"reading": "いろ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "すきないろはなんですか。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '歌', 'bài hát', '歌が好きです。', '{"reading": "うた", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "うたがすきです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '歌う', 'hát', 'みんなで歌います。', '{"reading": "うたう", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "みんなでうたいます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '海', 'biển', '夏は海に行きます。', '{"reading": "うみ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "なつはうみにいきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '売る', 'bán', '本を売ります。', '{"reading": "うる", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "ほんをうります。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '映画', 'phim điện ảnh', '映画を見ます。', '{"reading": "えいが", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "えいがをみます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '英語', 'tiếng Anh', '英語を勉強します。', '{"reading": "えいご", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "えいごをべんきょうします。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '駅', 'nhà ga', '駅で会いましょう。', '{"reading": "えき", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "えきであいましょう。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '鉛筆', 'bút chì', '鉛筆で書きます。', '{"reading": "えんぴつ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "えんぴつでかきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '美味しい', 'ngon', 'このケーキは美味しいです。', '{"reading": "おいしい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "このけーきはおいしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '多い', 'nhiều', '学生が多いです。', '{"reading": "おおい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "がくせいがおおいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '大きい', 'to, lớn', 'この家は大きいです。', '{"reading": "おおきい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "このいえはおおきいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), 'お母さん', 'mẹ', 'お母さんは優しいです。', '{"reading": "おかあさん", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "おかあさんはやさしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), 'お金', 'tiền', 'お金がありません。', '{"reading": "おかね", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "おかねがありません。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '起きる', 'thức dậy', '毎朝六時に起きます。', '{"reading": "おきる", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "まいあさろくじにおきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '置く', 'đặt, để', '本を机に置きます。', '{"reading": "おく", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "ほんをつくえにおきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '遅い', 'muộn, chậm', '電車が遅いです。', '{"reading": "おそい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "でんしゃがおそいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '弟', 'em trai', '弟は元気です。', '{"reading": "おとうと", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "おとうとはげんきです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '男', 'đàn ông', 'あの男は先生です。', '{"reading": "おとこ", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "あのおとこはせんせいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '同じ', 'giống nhau', '私と同じ意見です。', '{"reading": "おなじ", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "わたしとおなじいけんです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), 'お腹', 'bụng', 'お腹が痛いです。', '{"reading": "おなか", "partOfSpeech": "noun", "jlptLevel": "N5", "exampleReading": "おなかがいたいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '覚える', 'nhớ, ghi nhớ', '単語を覚えます。', '{"reading": "おぼえる", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "たんごをおぼえます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '重い', 'nặng', 'この荷物は重いです。', '{"reading": "おもい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "このにもつはおもいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '面白い', 'thú vị', 'この本は面白いです。', '{"reading": "おもしろい", "partOfSpeech": "adjective", "jlptLevel": "N5", "exampleReading": "このほんはおもしろいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '泳ぐ', 'bơi', 'プールで泳ぎます。', '{"reading": "およぐ", "partOfSpeech": "verb", "jlptLevel": "N5", "exampleReading": "ぷーるでおよぎます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '盗む', 'ăn trộm', '彼はお金を盗みました。', '{"reading": "ぬすむ", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "かれはおかねをぬすみました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '生きる', 'sống', '祖父は九十歳まで生きました。', '{"reading": "いきる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "そふはきゅうじゅっさいまでいきました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '苦い', 'đắng', 'この薬は苦いです。', '{"reading": "にがい", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "このくすりはにがいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '沸く', 'sôi (nước)', 'お湯が沸きました。', '{"reading": "わく", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "おゆがわきました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '意見', 'ý kiến', '彼の意見に賛成です。', '{"reading": "いけん", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "かれのいけんにさんせいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '漫画', 'truyện tranh', '漫画を読むのが好きです。', '{"reading": "まんが", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "まんがをよむのがすきです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '医学', 'y học', '彼女は医学を勉強しています。', '{"reading": "いがく", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "かのじょはいがくをべんきょうしています。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '折る', 'bẻ, gãy', '紙を半分に折ります。', '{"reading": "おる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "かみをはんぶんにおります。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '聞こえる', 'nghe thấy', '音楽が聞こえます。', '{"reading": "きこえる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "おんがくがきこえます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '必ず', 'chắc chắn', '明日は必ず来てください。', '{"reading": "かならず", "partOfSpeech": "adverb", "jlptLevel": "N4", "exampleReading": "あしたはかならずきてください。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '壊す', 'làm hỏng', 'おもちゃを壊しました。', '{"reading": "こわす", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "おもちゃをこわしました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '怒る', 'tức giận', '先生が怒りました。', '{"reading": "おこる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "せんせいがおこりました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '床屋', 'tiệm cắt tóc', '床屋で髪を切りました。', '{"reading": "とこや", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "とこやでかみをきりました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '運動する', 'tập thể dục', '毎日運動します。', '{"reading": "うんどうする", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "まいにちうんどうします。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '止む', 'ngừng (mưa)', '雨が止みました。', '{"reading": "やむ", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "あめがやみました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '表', 'mặt trước, bề mặt', '家の表に立っています。', '{"reading": "おもて", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "いえのおもてにたっています。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '大学生', 'sinh viên đại học', '兄は大学生です。', '{"reading": "だいがくせい", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "あにはだいがくせいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '運転手', 'tài xế', '彼はバスの運転手です。', '{"reading": "うんてんしゅ", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "かれはばすのうんてんしゅです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '予習', 'sự chuẩn bị bài trước', '今晩予習をします。', '{"reading": "よしゅう", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "こんばんよしゅうをします。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '心配する', 'lo lắng', '母は私を心配しています。', '{"reading": "しんぱいする", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "はははわたしをしんぱいしています。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '柔らかい', 'mềm', 'このパンは柔らかいです。', '{"reading": "やわらかい", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "このぱんはやわらかいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '拾う', 'nhặt lên', '財布を拾いました。', '{"reading": "ひろう", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "さいふをひろいました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '気', 'tinh thần, tâm trạng', '気をつけてください。', '{"reading": "き", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "きをつけてください。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '比べる', 'so sánh', '二つの値段を比べます。', '{"reading": "くらべる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "ふたつのねだんをくらべます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '郊外', 'ngoại ô', '郊外に住んでいます。', '{"reading": "こうがい", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "こうがいにすんでいます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '正月', 'Tết Nguyên đán (Nhật)', '正月に家族と過ごします。', '{"reading": "しょうがつ", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "しょうがつにかぞくとすごします。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '規則', 'quy tắc', '学校の規則を守ります。', '{"reading": "きそく", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "がっこうのきそくをまもります。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '発音', 'phát âm', '彼の発音はきれいです。', '{"reading": "はつおん", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "かれのはつおんはきれいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '焼く', 'nướng', 'パンを焼きます。', '{"reading": "やく", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "ぱんをやきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '屋上', 'sân thượng', '屋上から町が見えます。', '{"reading": "おくじょう", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "おくじょうからまちがみえます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '失礼', 'sự bất lịch sự, xin lỗi', '失礼ですが、お名前は？', '{"reading": "しつれい", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "しつれいですが、おなまえは？"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '点', 'điểm số', 'テストでいい点を取りました。', '{"reading": "てん", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "てすとでいいてんをとりました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '一生懸命', 'hết sức, nỗ lực', '一生懸命勉強します。', '{"reading": "いっしょうけんめい", "partOfSpeech": "adverb", "jlptLevel": "N4", "exampleReading": "いっしょうけんめいべんきょうします。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '今度', 'lần này, lần sau', '今度一緒に行きましょう。', '{"reading": "こんど", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "こんどいっしょにいきましょう。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '機会', 'cơ hội', 'いい機会がありました。', '{"reading": "きかい", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "いいきかいがありました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '建てる', 'xây dựng', '新しい家を建てます。', '{"reading": "たてる", "partOfSpeech": "verb", "jlptLevel": "N4", "exampleReading": "あたらしいいえをたてます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '複雑', 'phức tạp', 'この問題は複雑です。', '{"reading": "ふくざつ", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "このもんだいはふくざつです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '彼', 'anh ấy, bạn trai', '彼は優しいです。', '{"reading": "かれ", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "かれはやさしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '布団', 'futon (chăn đệm)', '布団を敷きます。', '{"reading": "ふとん", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "ふとんをしきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '大事', 'quan trọng', '健康はとても大事です。', '{"reading": "だいじ", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "けんこうはとてもだいじです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '贈り物', 'món quà', '友達に贈り物をあげます。', '{"reading": "おくりもの", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "ともだちにおくりものをあげます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '泥棒', 'kẻ trộm', '昨日泥棒が来ました。', '{"reading": "どろぼう", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "きのうどろぼうがきました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '注意', 'sự chú ý, cẩn thận', '車に注意してください。', '{"reading": "ちゅうい", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "くるまにちゅういしてください。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '台風', 'bão', '今週台風が来ます。', '{"reading": "たいふう", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "こんしゅうたいふうがきます。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '日', 'mặt trời, ngày', '日が昇りました。', '{"reading": "ひ", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "ひがのぼりました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '必要', 'cần thiết', '水は必要です。', '{"reading": "ひつよう", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "みずはひつようです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '僕', 'tôi (nam giới dùng)', '僕は学生です。', '{"reading": "ぼく", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "ぼくはがくせいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '地震', 'động đất', '昨夜大きい地震がありました。', '{"reading": "じしん", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "さくやおおきいじしんがありました。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '厳しい', 'nghiêm khắc', '父はとても厳しいです。', '{"reading": "きびしい", "partOfSpeech": "adjective", "jlptLevel": "N4", "exampleReading": "ちちはとてもきびしいです。"}'::jsonb),
  ((SELECT id FROM language WHERE code = 'ja'), '葉', 'chiếc lá', '秋に葉が落ちます。', '{"reading": "は", "partOfSpeech": "noun", "jlptLevel": "N4", "exampleReading": "あきにはがおちます。"}'::jsonb)
) AS seed (language_id, word, meaning, example, attributes);

INSERT INTO vocabulary_tag_link (vocabulary_id, tag_id)
SELECT v.id, t.id FROM vocabulary v
JOIN vocabulary_tag t
    ON t.user_id = v.user_id
   AND t.name = COALESCE(v.attributes ->> 'cefrLevel', v.attributes ->> 'hskLevel', v.attributes ->> 'jlptLevel')
WHERE v.user_id = (SELECT id FROM app_user WHERE email = 'seed@learnflow.system');

-- Backfill: clone the starter pack into every account that existed before this migration — they
-- lost it when V11 wiped business data with no recorded owner. Safe to run unconditionally (this
-- migration only ever executes once): accounts that already manually added their own words just
-- get the starter pack added alongside them, nothing is overwritten or deduplicated against.
INSERT INTO vocabulary (user_id, language_id, word, meaning, example, attributes, created_at, updated_at)
SELECT u.id, v.language_id, v.word, v.meaning, v.example, v.attributes, now(), now()
FROM app_user u
CROSS JOIN vocabulary v
WHERE v.user_id = (SELECT id FROM app_user WHERE email = 'seed@learnflow.system')
  AND u.email <> 'seed@learnflow.system';

INSERT INTO vocabulary_tag (user_id, name)
SELECT u.id, t.name
FROM app_user u
CROSS JOIN (VALUES ('A1'), ('A2'), ('HSK1'), ('HSK2'), ('N5'), ('N4')) AS t (name)
WHERE u.email <> 'seed@learnflow.system';

INSERT INTO vocabulary_tag_link (vocabulary_id, tag_id)
SELECT v.id, t.id FROM vocabulary v
JOIN vocabulary_tag t
    ON t.user_id = v.user_id
   AND t.name = COALESCE(v.attributes ->> 'cefrLevel', v.attributes ->> 'hskLevel', v.attributes ->> 'jlptLevel')
WHERE t.name IN ('A1', 'A2', 'HSK1', 'HSK2', 'N5', 'N4')
  AND v.user_id <> (SELECT id FROM app_user WHERE email = 'seed@learnflow.system');

-- SRS schedule for every newly cloned word — same "missing schedule" backfill pattern as V10,
-- excluding the template account itself (it is never reviewed).
INSERT INTO review_schedule (vocabulary_id, user_id, next_review)
SELECT v.id, v.user_id, now()
FROM vocabulary v
LEFT JOIN review_schedule rs ON rs.vocabulary_id = v.id
WHERE rs.vocabulary_id IS NULL
  AND v.user_id <> (SELECT id FROM app_user WHERE email = 'seed@learnflow.system');
